config/routes.rb
CheckMeOut360::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "my_devise/registrations", :sessions => "my_devise/sessions" } do
    get "users/sign_in" => 'walls#index'
    get "users/sign_up" => 'walls#index'
  end
<<<<<<< HEAD
  
  resources :categories do
  end
  
=======

  resources :categories
  resources :user_extras
>>>>>>> 12333d4f6f027208e5fc5e9f7dacb8abb9671793
  resources :home, only: [:index] do
    collection do
      get 'about'
      get 'contact'
      get 'help'
      get 'who'
    end
  end
  resources :users do
    resources :places do
      collection do
        get 'map'
        get 'all_places'
        get 'sync'
      end
    end
    resources :checkins do
      collection do
        get 'sync'
      end
    end
  end

  resources :statistics, only: [:index, :map, :graph] do
    collection do
      get 'map'
      get 'graph'
      get 'pie'
      get 'line'
      get 'bar'
      get 'all_places'
    end
  end

  root :to => 'home#index'

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    render :line
  end
  
  def map
  end
  
  def line
  end
  
  def pie
  end
  
  def bar
  end
  
  def all_places
    @places = Place.all
    respond_to do |format|
      format.json { render :json => @places }
    end
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/_stats_header.html.erb
<div id="stats_header" class="list-widget">
  <a><%= image_tag "graphs.png", size: "42x42", class: "avatar left" %>
  <div class="list-head">
    <h3><a class="no-dec">Graphs</a></h3>
      <div class="no-dec list-meta">
        Your data visualized
      </div>
  </div>
  <ul>
      <li class="right_tab">
        &rsaquo; <%=link_to "total checkins", line_statistics_path, class: "purple" %><br/>
      </li>
      <li class="right_tab">
        &rsaquo; <%=link_to "top places", bar_statistics_path, class: "purple" %><br/>
      </li>
      <li><%= link_to "View All Checkins ›", map_statistics_path, class: "list-view" %></li>
  </ul>
</div>

app/views/statistics/bar.html.erb
<%= render partial: "stats_header" %>

  <script type="text/javascript" charset="utf-8">
    $(function() {
      // THEME
      Highcharts.theme = {
         colors: ["#DDDF0D", "#7798BF", "#55BF3B", "#DF5353", "#aaeeee", "#ff0066", "#eeaaee",
            "#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],
         chart: {
            backgroundColor: {
               linearGradient: [0, 0, 0, 400],
               stops: [
                  [0, 'rgb(96, 96, 96)'],
                  [1, 'rgb(16, 16, 16)']
               ]
            },
            borderWidth: 0,
            borderRadius: 15,
            plotBackgroundColor: null,
            plotShadow: false,
            plotBorderWidth: 0
         },
         title: {
            style: {
               color: '#FFF',
               font: '16px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
            }
         },
         subtitle: {
            style: {
               color: '#DDD',
               font: '12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
            }
         },
         xAxis: {
            gridLineWidth: 0,
            lineColor: '#999',
            tickColor: '#999',
            labels: {
               style: {
                  color: '#999',
                  fontWeight: 'bold'
               }
            },
            title: {
               style: {
                  color: '#AAA',
                  font: 'bold 12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
               }
            }
         },
         yAxis: {
            alternateGridColor: null,
            minorTickInterval: null,
            gridLineColor: 'rgba(255, 255, 255, .1)',
            lineWidth: 0,
            tickWidth: 0,
            labels: {
               style: {
                  color: '#999',
                  fontWeight: 'bold'
               }
            },
            title: {
               style: {
                  color: '#AAA',
                  font: 'bold 12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
               }
            }
         },
         legend: {
            itemStyle: {
               color: '#CCC'
            },
            itemHoverStyle: {
               color: '#FFF'
            },
            itemHiddenStyle: {
               color: '#333'
            }
         },
         labels: {
            style: {
               color: '#CCC'
            }
         },
         tooltip: {
            backgroundColor: {
               linearGradient: [0, 0, 0, 50],
               stops: [
                  [0, 'rgba(96, 96, 96, .8)'],
                  [1, 'rgba(16, 16, 16, .8)']
               ]
            },
            borderWidth: 0,
            style: {
               color: '#FFF'
            }
         },


         plotOptions: {
            line: {
               dataLabels: {
                  color: '#CCC'
               },
               marker: {
                  lineColor: '#333'
               }
            },
            spline: {
               marker: {
                  lineColor: '#333'
               }
            },
            scatter: {
               marker: {
                  lineColor: '#333'
               }
            },
            candlestick: {
               lineColor: 'white'
            }
         },

         toolbar: {
            itemStyle: {
               color: '#CCC'
            }
         },

         navigation: {
            buttonOptions: {
               backgroundColor: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#606060'],
                     [0.6, '#333333']
                  ]
               },
               borderColor: '#000000',
               symbolStroke: '#C0C0C0',
               hoverSymbolStroke: '#FFFFFF'
            }
         },

         exporting: {
            buttons: {
               exportButton: {
                  symbolFill: '#55BE3B'
               },
               printButton: {
                  symbolFill: '#7797BE'
               }
            }
         },

         // scroll charts
         rangeSelector: {
            buttonTheme: {
               fill: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#888'],
                     [0.6, '#555']
                  ]
               },
               stroke: '#000000',
               style: {
                  color: '#CCC',
                  fontWeight: 'bold'
               },
               states: {
                  hover: {
                     fill: {
                        linearGradient: [0, 0, 0, 20],
                        stops: [
                           [0.4, '#BBB'],
                           [0.6, '#888']
                        ]
                     },
                     stroke: '#000000',
                     style: {
                        color: 'white'
                     }
                  },
                  select: {
                     fill: {
                        linearGradient: [0, 0, 0, 20],
                        stops: [
                           [0.1, '#000'],
                           [0.3, '#333']
                        ]
                     },
                     stroke: '#000000',
                     style: {
                        color: 'yellow'
                     }
                  }
               }
            },
            inputStyle: {
               backgroundColor: '#333',
               color: 'silver'
            },
            labelStyle: {
               color: 'silver'
            }
         },

         navigator: {
            handles: {
               backgroundColor: '#666',
               borderColor: '#AAA'
            },
            outlineColor: '#CCC',
            maskFill: 'rgba(16, 16, 16, 0.5)',
            series: {
               color: '#7798BF',
               lineColor: '#A6C7ED'
            }
         },

         scrollbar: {
            barBackgroundColor: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#888'],
                     [0.6, '#555']
                  ]
               },
            barBorderColor: '#CCC',
            buttonArrowColor: '#CCC',
            buttonBackgroundColor: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#888'],
                     [0.6, '#555']
                  ]
               },
            buttonBorderColor: '#CCC',
            rifleColor: '#FFF',
            trackBackgroundColor: {
               linearGradient: [0, 0, 0, 10],
               stops: [
                  [0, '#000'],
                  [1, '#333']
               ]
            },
            trackBorderColor: '#666'
         },

         // special colors for some of the demo examples
         legendBackgroundColor: 'rgba(48, 48, 48, 0.8)',
         legendBackgroundColorSolid: 'rgb(70, 70, 70)',
         dataLabelsColor: '#444',
         textColor: '#E0E0E0',
         maskColor: 'rgba(255,255,255,0.3)'
      };

      // Apply the theme
      var highchartsOptions = Highcharts.setOptions(Highcharts.theme);
      
      // BAR CHART
            <% top_places = Place.top_places %>
            bar_chart = new Highcharts.Chart({
                chart: {
                  renderTo: 'bar_chart',
                  type: 'bar'
                },
                title: {
                  text: 'Top Places'
                },
                subtitle: {
                  text: 'Highest Visits'
                },
                xAxis: {
                  categories: [
                    <% top_places.keys.each_with_index do |key,index| %>
                      <% if index == top_places.length-1 %>
                        "<%= key %>"
                        <% break %>
                      <% end %>
                      "<%= key %>",
                    <% end %>
                  ],
                  title: {
                    text: null
                  }
                },
                yAxis: {
                  min: 0,
                  title: {
                    text: 'Checkin Count',
                    align: 'high'
                  }
                },
                tooltip: {
                  formatter: function() {
                    return ''+
                      this.series.name +': '+ this.y;
                  }
                },
                plotOptions: {
                  bar: {
                    dataLabels: {
                      enabled: true
                    }
                  }
                },
                legend: {
                  layout: 'vertical',
                  align: 'right',
                  verticalAlign: 'top',
                  x: -100,
                  y: 100,
                  floating: true,
                  borderWidth: 1,
                  backgroundColor: '#FFFFFF',
                  shadow: true
                },
                credits: {
                  enabled: false
                },
                  series: [{
                  name: 'Most Visited Places',
                  data: <%= top_places.values %>
                }]
              });

});
  </script>
<div class="charts" id="bar_chart"></div>

app/views/statistics/index.html.erb
<div id="home_page">
  <%= render partial: "stats_header" %>
</div>

app/views/statistics/line.html.erb
<%= render partial: "stats_header" %>

  <script type="text/javascript" charset="utf-8">
    $(function() {
      // THEME
      Highcharts.theme = {
         colors: ["#DDDF0D", "#7798BF", "#55BF3B", "#DF5353", "#aaeeee", "#ff0066", "#eeaaee",
            "#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],
         chart: {
            backgroundColor: {
               linearGradient: [0, 0, 0, 400],
               stops: [
                  [0, 'rgb(96, 96, 96)'],
                  [1, 'rgb(16, 16, 16)']
               ]
            },
            borderWidth: 0,
            borderRadius: 15,
            plotBackgroundColor: null,
            plotShadow: false,
            plotBorderWidth: 0
         },
         title: {
            style: {
               color: '#FFF',
               font: '16px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
            }
         },
         subtitle: {
            style: {
               color: '#DDD',
               font: '12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
            }
         },
         xAxis: {
            gridLineWidth: 0,
            lineColor: '#999',
            tickColor: '#999',
            labels: {
               style: {
                  color: '#999',
                  fontWeight: 'bold'
               }
            },
            title: {
               style: {
                  color: '#AAA',
                  font: 'bold 12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
               }
            }
         },
         yAxis: {
            alternateGridColor: null,
            minorTickInterval: null,
            gridLineColor: 'rgba(255, 255, 255, .1)',
            lineWidth: 0,
            tickWidth: 0,
            labels: {
               style: {
                  color: '#999',
                  fontWeight: 'bold'
               }
            },
            title: {
               style: {
                  color: '#AAA',
                  font: 'bold 12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
               }
            }
         },
         legend: {
            itemStyle: {
               color: '#CCC'
            },
            itemHoverStyle: {
               color: '#FFF'
            },
            itemHiddenStyle: {
               color: '#333'
            }
         },
         labels: {
            style: {
               color: '#CCC'
            }
         },
         tooltip: {
            backgroundColor: {
               linearGradient: [0, 0, 0, 50],
               stops: [
                  [0, 'rgba(96, 96, 96, .8)'],
                  [1, 'rgba(16, 16, 16, .8)']
               ]
            },
            borderWidth: 0,
            style: {
               color: '#FFF'
            }
         },


         plotOptions: {
            line: {
               dataLabels: {
                  color: '#CCC'
               },
               marker: {
                  lineColor: '#333'
               }
            },
            spline: {
               marker: {
                  lineColor: '#333'
               }
            },
            scatter: {
               marker: {
                  lineColor: '#333'
               }
            },
            candlestick: {
               lineColor: 'white'
            }
         },

         toolbar: {
            itemStyle: {
               color: '#CCC'
            }
         },

         navigation: {
            buttonOptions: {
               backgroundColor: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#606060'],
                     [0.6, '#333333']
                  ]
               },
               borderColor: '#000000',
               symbolStroke: '#C0C0C0',
               hoverSymbolStroke: '#FFFFFF'
            }
         },

         exporting: {
            buttons: {
               exportButton: {
                  symbolFill: '#55BE3B'
               },
               printButton: {
                  symbolFill: '#7797BE'
               }
            }
         },

         // scroll charts
         rangeSelector: {
            buttonTheme: {
               fill: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#888'],
                     [0.6, '#555']
                  ]
               },
               stroke: '#000000',
               style: {
                  color: '#CCC',
                  fontWeight: 'bold'
               },
               states: {
                  hover: {
                     fill: {
                        linearGradient: [0, 0, 0, 20],
                        stops: [
                           [0.4, '#BBB'],
                           [0.6, '#888']
                        ]
                     },
                     stroke: '#000000',
                     style: {
                        color: 'white'
                     }
                  },
                  select: {
                     fill: {
                        linearGradient: [0, 0, 0, 20],
                        stops: [
                           [0.1, '#000'],
                           [0.3, '#333']
                        ]
                     },
                     stroke: '#000000',
                     style: {
                        color: 'yellow'
                     }
                  }
               }
            },
            inputStyle: {
               backgroundColor: '#333',
               color: 'silver'
            },
            labelStyle: {
               color: 'silver'
            }
         },

         navigator: {
            handles: {
               backgroundColor: '#666',
               borderColor: '#AAA'
            },
            outlineColor: '#CCC',
            maskFill: 'rgba(16, 16, 16, 0.5)',
            series: {
               color: '#7798BF',
               lineColor: '#A6C7ED'
            }
         },

         scrollbar: {
            barBackgroundColor: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#888'],
                     [0.6, '#555']
                  ]
               },
            barBorderColor: '#CCC',
            buttonArrowColor: '#CCC',
            buttonBackgroundColor: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#888'],
                     [0.6, '#555']
                  ]
               },
            buttonBorderColor: '#CCC',
            rifleColor: '#FFF',
            trackBackgroundColor: {
               linearGradient: [0, 0, 0, 10],
               stops: [
                  [0, '#000'],
                  [1, '#333']
               ]
            },
            trackBorderColor: '#666'
         },

         // special colors for some of the demo examples
         legendBackgroundColor: 'rgba(48, 48, 48, 0.8)',
         legendBackgroundColorSolid: 'rgb(70, 70, 70)',
         dataLabelsColor: '#444',
         textColor: '#E0E0E0',
         maskColor: 'rgba(255,255,255,0.3)'
      };

      // Apply the theme
      var highchartsOptions = Highcharts.setOptions(Highcharts.theme);
      
      
      // LINE CHART
      line_chart = new Highcharts.Chart({
                  chart: {
                      renderTo: 'line_chart',
                      type: 'line',
                      marginRight: 130,
                      marginBottom: 25
                  },
                  title: {
                      text: 'Monthly Checkins',
                      x: -20 //center
                  },
                  subtitle: {
                      text: 'Grouped by months',
                      x: -20
                  },
                  xAxis: {
                      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
                  },
                  yAxis: {
                      title: {
                          text: 'Checkins'
                      },
                      plotLines: [{
                          value: 0,
                          width: 1,
                          color: '#808080'
                      }]
                  },
                  tooltip: {
                      formatter: function() {
                              return '<b>'+ this.series.name +'</b><br/>'+
                              this.x +': '+ this.y +'°Checkins';
                      }
                  },
                  legend: {
                      layout: 'vertical',
                      align: 'right',
                      verticalAlign: 'top',
                      x: -10,
                      y: 100,
                      borderWidth: 0
                  },
                  series: [
                  <% for year in Checkin.oldest_checkin.created_at.year..Time.now.year-1 %>
                    {
                        name: <%= year %>,
                        data: <%= Checkin.checkins_count_by_month(year) %>
                    },
                  <% end %>
                  {
                      name: <%= Time.now.year %>,
                      data: <%= Checkin.checkins_count_by_month(Time.now.year) %>
                  }
                  ]
              });
});
  </script>
<div class="charts" id="line_chart"></div>

app/views/statistics/map.html.erb
<div id="stats_maps">
  <%= render partial: "places/google_map" %>
</div>

app/views/statistics/pie.html.erb
<%= render partial: "stats_header" %>

  <script type="text/javascript" charset="utf-8">
    $(function() {
      // THEME
      Highcharts.theme = {
         colors: ["#DDDF0D", "#7798BF", "#55BF3B", "#DF5353", "#aaeeee", "#ff0066", "#eeaaee",
            "#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],
         chart: {
            backgroundColor: {
               linearGradient: [0, 0, 0, 400],
               stops: [
                  [0, 'rgb(96, 96, 96)'],
                  [1, 'rgb(16, 16, 16)']
               ]
            },
            borderWidth: 0,
            borderRadius: 15,
            plotBackgroundColor: null,
            plotShadow: false,
            plotBorderWidth: 0
         },
         title: {
            style: {
               color: '#FFF',
               font: '16px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
            }
         },
         subtitle: {
            style: {
               color: '#DDD',
               font: '12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
            }
         },
         xAxis: {
            gridLineWidth: 0,
            lineColor: '#999',
            tickColor: '#999',
            labels: {
               style: {
                  color: '#999',
                  fontWeight: 'bold'
               }
            },
            title: {
               style: {
                  color: '#AAA',
                  font: 'bold 12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
               }
            }
         },
         yAxis: {
            alternateGridColor: null,
            minorTickInterval: null,
            gridLineColor: 'rgba(255, 255, 255, .1)',
            lineWidth: 0,
            tickWidth: 0,
            labels: {
               style: {
                  color: '#999',
                  fontWeight: 'bold'
               }
            },
            title: {
               style: {
                  color: '#AAA',
                  font: 'bold 12px Lucida Grande, Lucida Sans Unicode, Verdana, Arial, Helvetica, sans-serif'
               }
            }
         },
         legend: {
            itemStyle: {
               color: '#CCC'
            },
            itemHoverStyle: {
               color: '#FFF'
            },
            itemHiddenStyle: {
               color: '#333'
            }
         },
         labels: {
            style: {
               color: '#CCC'
            }
         },
         tooltip: {
            backgroundColor: {
               linearGradient: [0, 0, 0, 50],
               stops: [
                  [0, 'rgba(96, 96, 96, .8)'],
                  [1, 'rgba(16, 16, 16, .8)']
               ]
            },
            borderWidth: 0,
            style: {
               color: '#FFF'
            }
         },


         plotOptions: {
            line: {
               dataLabels: {
                  color: '#CCC'
               },
               marker: {
                  lineColor: '#333'
               }
            },
            spline: {
               marker: {
                  lineColor: '#333'
               }
            },
            scatter: {
               marker: {
                  lineColor: '#333'
               }
            },
            candlestick: {
               lineColor: 'white'
            }
         },

         toolbar: {
            itemStyle: {
               color: '#CCC'
            }
         },

         navigation: {
            buttonOptions: {
               backgroundColor: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#606060'],
                     [0.6, '#333333']
                  ]
               },
               borderColor: '#000000',
               symbolStroke: '#C0C0C0',
               hoverSymbolStroke: '#FFFFFF'
            }
         },

         exporting: {
            buttons: {
               exportButton: {
                  symbolFill: '#55BE3B'
               },
               printButton: {
                  symbolFill: '#7797BE'
               }
            }
         },

         // scroll charts
         rangeSelector: {
            buttonTheme: {
               fill: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#888'],
                     [0.6, '#555']
                  ]
               },
               stroke: '#000000',
               style: {
                  color: '#CCC',
                  fontWeight: 'bold'
               },
               states: {
                  hover: {
                     fill: {
                        linearGradient: [0, 0, 0, 20],
                        stops: [
                           [0.4, '#BBB'],
                           [0.6, '#888']
                        ]
                     },
                     stroke: '#000000',
                     style: {
                        color: 'white'
                     }
                  },
                  select: {
                     fill: {
                        linearGradient: [0, 0, 0, 20],
                        stops: [
                           [0.1, '#000'],
                           [0.3, '#333']
                        ]
                     },
                     stroke: '#000000',
                     style: {
                        color: 'yellow'
                     }
                  }
               }
            },
            inputStyle: {
               backgroundColor: '#333',
               color: 'silver'
            },
            labelStyle: {
               color: 'silver'
            }
         },

         navigator: {
            handles: {
               backgroundColor: '#666',
               borderColor: '#AAA'
            },
            outlineColor: '#CCC',
            maskFill: 'rgba(16, 16, 16, 0.5)',
            series: {
               color: '#7798BF',
               lineColor: '#A6C7ED'
            }
         },

         scrollbar: {
            barBackgroundColor: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#888'],
                     [0.6, '#555']
                  ]
               },
            barBorderColor: '#CCC',
            buttonArrowColor: '#CCC',
            buttonBackgroundColor: {
                  linearGradient: [0, 0, 0, 20],
                  stops: [
                     [0.4, '#888'],
                     [0.6, '#555']
                  ]
               },
            buttonBorderColor: '#CCC',
            rifleColor: '#FFF',
            trackBackgroundColor: {
               linearGradient: [0, 0, 0, 10],
               stops: [
                  [0, '#000'],
                  [1, '#333']
               ]
            },
            trackBorderColor: '#666'
         },

         // special colors for some of the demo examples
         legendBackgroundColor: 'rgba(48, 48, 48, 0.8)',
         legendBackgroundColorSolid: 'rgb(70, 70, 70)',
         dataLabelsColor: '#444',
         textColor: '#E0E0E0',
         maskColor: 'rgba(255,255,255,0.3)'
      };

      // Apply the theme
      var highchartsOptions = Highcharts.setOptions(Highcharts.theme);          
      // PIE CHART
          pie_chart = new Highcharts.Chart({
              chart: {
                renderTo: 'pie_chart',
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
              },
              title: {
                text: 'Where we been for <%= Time.now.strftime("on %B %Y")%>?'
              },
              tooltip: {
                formatter: function() {
                  return '<b>'+ this.point.name +'</b>: '+ this.percentage +' %';
                }
              },
              plotOptions: {
                pie: {
                  allowPointSelect: true,
                  cursor: 'pointer',
                  dataLabels: {
                    enabled: true,
                    color: '#000000',
                    connectorColor: '#000000',
                    formatter: function() {
                      return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
                    }
                  }
                }
              },
              series: [{
                type: 'pie',
                name: 'places category',
                data: [
                  <% categories = Place.categories(Time.now) %>
                  <% categories.each_with_index do |category, index| %>
                    <% if index == categories.length-1 %>
                      ['<%= "#{category}" %>',   <%= Place.places_for_categories(category).count %>]
                      <% break %>
                    <% end %>
                    ['<%= "#{category}" %>',   <%= Place.places_for_categories(category).count %>],
                  <% end %>
                ]
              }]
            });

});
  </script>
  
<div class="charts" id="pie_chart"></div>
  