config/routes.rb
CheckMeOut360::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "my_devise/registrations", :sessions => "my_devise/sessions" } do
    get "users/sign_in" => 'walls#index'
    get "users/sign_up" => 'walls#index'
  end
<<<<<<< HEAD
  
  resources :categories do
  end
  
=======

  resources :categories
  resources :user_extras
>>>>>>> 12333d4f6f027208e5fc5e9f7dacb8abb9671793
  resources :home, only: [:index] do
    collection do
      get 'about'
      get 'contact'
      get 'help'
      get 'who'
    end
  end
  resources :users do
    resources :places do
      collection do
        get 'map'
        get 'all_places'
        get 'sync'
      end
    end
    resources :checkins do
      collection do
        get 'sync'
      end
    end
  end

  resources :statistics, only: [:index, :map, :graph] do
    collection do
      get 'map'
      get 'graph'
      get 'pie'
      get 'line'
      get 'bar'
      get 'all_places'
    end
  end

  root :to => 'home#index'

end

app/views/shared/_ajax_loader.html.erb
<div id="<%=div_id%>_loader_circle" style="display:none;">
  <br/>
  <center>
    <%= image_tag "ajax-loader.gif" %>
    <br/>
    <br/>
    <p> Retrieving Your Facebook Places and Checkins...</p>
  </center>
</div>

app/views/shared/_checkins_summary.html.erb
<div class="list-widget">
  <a><%= image_tag "marker_icon.png", size: "42x42", class: "avatar left" %>
  <div class="list-head">
    <h3><a class="no-dec">Latest Checkin</a></h3>
      <div class="no-dec list-meta"> 
        <a>Total Checkins</a> · <%= @checkins.count %>
      </div>
  </div>
  <ul>
      <li>
          <div>
            <a class="purple no_dec">Message »</a><i class="grey"> <%= @latest_checkin.message || "Checkin!" %></i>
          </div>
      </li>
      <li>
          <div>
            <a class="purple no_dec">Place »</a><i class="grey"> <%= @latest_checkin.place.name %></i>
          </div>
      </li>
      <li>
          <div>
            <a class="purple no_dec">Time »</a><i class="grey"> <%= @latest_checkin.created_at.strftime("on %A %B %d, %Y at %I:%M %p")%></i>
          </div>
      </li>
      <li><%= link_to "View All Checkins ›", user_checkins_path(current_user), class: "list-view" %></li>
  </ul>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, message|
  puts key.inspect + message.inspect
  if message == I18n.t("devise.failure.invalid")
    html_key = 'error'
  elsif key == :notice 
    html_key = 'success'
  else
    html_key = key
  end
%>
<div class="alert-message <%=html_key%>" data-alert="alert">
  <a class="close" href="#">×</a>
  <p><%=message%></p>
</div>
<% end %>

app/views/shared/_flash.js.erb
$('#flash').empty();
$('#flash').html('<%= strip_new_line(render("shared/flash.html.erb", :flash => flash)).html_safe %>');

app/views/shared/_getting_started.html.erb
<%= image_tag "school_of_engineering_banner.jpg", :size => "560x150"%>
<h3>Welcome!</h3>
<h3>Getting Started</h3>
<p>
  <b>Register by signing in: </b>Click the <i>Register</i> button above to get started
  <br/>
  <b>Register using Facebook: </b>Click the <i>Facebook</i> image above to sign in using Facebook
  <br/>
</p>
<br/>
<hr/>
<h2>About The Site</h2>
<hr/>

app/views/shared/_mini_feed.html.erb
<div id="mini_feed">
  <% @all_checkins.each_with_index do |checkin, index| %>
    <a>
      <% checkin.users.each_with_index do |user, index| %>
        <% if index > 3 %>
          <small style="font-size: 10px;">...</small>
          <% break %>
        <% elsif index == checkin.users.count-1 %>
          <small style="font-size: 10px;"><%= link_to user.name, user_path(user), :class => "user_checkin_list" %></small>
        <% else %>
          <small style="font-size: 10px;"><%= link_to user.name, user_path(user), :class => "user_checkin_list" %></small>,
        <% end %>
      <% end %>
      <%= image_tag "marker_icon.png" %><small style="font-size: 10px;"><%= checkin.place.name %></small>
      <b>On</b> <small style="font-size: 10px;"><%= checkin.created_at.strftime("on %A") + " #{day_format(checkin.created_at)}" %></small>
      <hr/>
    </a>
  <% end %>
</div>

app/views/shared/_privacy.html.erb
<div class="list-widget">
  <a><%= image_tag "#{@user.privacy}_lock.png", id: "privacy_lock", size: "42x42", class: "avatar left" %>
  <div class="list-head">
    <h3><a class="no-dec">Security Setting</a></h3>
      <div class="no-dec list-meta">Current security level · <a><%= @user.privacy %></a>
      </div>
  </div>
  <ul>
  <% if current_user == @user %>
    <%= simple_form_for @user do |f| %>    
      <%= f.input :privacy, label: false, collection: User::PRIVACY, priority: User::PROTECTED, include_blank: false  %>
        <%= f.button :submit, class: "btn btn-success btn-small", value: "Update Settings" %>
    <% end %>
  <% end %>
  <div id="privacy_description_block">
    <p id="private"><i><small><b>&nbsp; private »</b></small></i> Only You <i><small><b>&nbsp; protected (default) »</b></small></i></i> Only friends <i><small><b>&nbsp; public »</b></small></i></small></i> everyone</p>
  </div>
  </ul>
</div>

app/views/shared/_profile_layout.html.erb
<div class="<%= span_class %>">
  <a><%= image_tag @user.picture, size: "42x42", class: "avatar left" %>
  <div class="list-head">
    <h3><a class="no-dec"><%= @user.name %></a></h3>

  </div>
  <ul>
    <div>
      <%= link_to "Myself »", user_path(@user.id), class: "btn btn-danger btn-mini" %> &nbsp;
      <%= link_to "Map »", map_user_places_path(@user.id), class: "btn btn-success btn-mini" %> &nbsp;
      <%= link_to "Places »", user_places_path(@user.id), class: "btn btn-info btn-mini user_show_places" %> &nbsp;
      <%= link_to "Checkins »", user_checkins_path(@user.id), class: "btn btn-warning btn-mini" %> &nbsp;
    </div>
  </ul>
</div>

app/views/shared/_sync_checkins.html.erb
<div class="main_content">
  <div class="hero-unit">
    <h2><small>getting started</small> Update your checkins </h2>
    <p>In order to get the latest data, you must sync your Facebook Checkin </p>
    <p>
      <%= link_to "Sync »", sync_user_checkins_path(@user.id), class: "btn btn-success btn-large" %> &nbsp;
    </p>
  </div>
</div>