config/routes.rb
CheckMeOut360::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "my_devise/registrations", :sessions => "my_devise/sessions" } do
    get "users/sign_in" => 'walls#index'
    get "users/sign_up" => 'walls#index'
  end
<<<<<<< HEAD
  
  resources :categories do
  end
  
=======

  resources :categories
  resources :user_extras
>>>>>>> 12333d4f6f027208e5fc5e9f7dacb8abb9671793
  resources :home, only: [:index] do
    collection do
      get 'about'
      get 'contact'
      get 'help'
      get 'who'
    end
  end
  resources :users do
    resources :places do
      collection do
        get 'map'
        get 'all_places'
        get 'sync'
      end
    end
    resources :checkins do
      collection do
        get 'sync'
      end
    end
  end

  resources :statistics, only: [:index, :map, :graph] do
    collection do
      get 'map'
      get 'graph'
      get 'pie'
      get 'line'
      get 'bar'
      get 'all_places'
    end
  end

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @all_checkins = Kaminari.paginate_array(Checkin.find(:all, order: "created_at desc")).page(params[:page])
  end

  def about
  end

  def contact
  end

  def who
    members = %w(Quy\ Phan Phu\ Phan Michael\ Luong Tan\ Cao Jake\ Pham)
    @users = []
    members.each do |member|
      user = User.find_by_name(member)
      user.get_profile_pic(user.token)
      @users << user
    end

  end

  def help
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_about_page.html.erb
<div>
  <%= render partial: "overview" %>
  <%= render partial: "technical" %>
  <br/>
  <strong>Check out the team!</strong>
  <%= link_to "Click Here", who_home_index_path %>
  <br/>
  <br/>
</div>

app/views/home/_getting_started.html.erb
  <div class="main_content">
    <div class="hero-unit">
      <h2><center><%=image_tag "instruction.png", size:"50x50" %> Instructions</center></h2>
      <hr/>
      <% if current_user %>
      <h3><small>Getting Started &#9658;</small> <%= link_to "Profile Page", user_path(current_user) %></h3>
        <h3><small>Then &#9658;</small> You will be able to see your <%= link_to "Profile", user_path(current_user) %> and set your <%= link_to "Security Settings", user_path(current_user) %> </h3>
        <h3><small>Finally &#9658;</small> View a <%= link_to "Map", map_user_places_path(current_user) %> of where you been, the <%= link_to "Places", user_places_path(current_user) %> and your <%= link_to "Checkins", user_places_path(current_user) %> </h3>
      <% else %>
        <h3><small>Getting Started &#9658;</small> <%= link_to "Sign in »", user_omniauth_authorize_path(:facebook) %></h3>
        <h3><small>Then &#9658;</small> You will be able to see your <small>Profile</small> and set your <small>Security Settings</small></h3>
        <h3><small>Finally &#9658;</small> View a <small>Map</small> of where you been, the <small>Places</small> and your <small>Checkins</small> </h3>
      <% end %>
      <h3><small>Just for fun &#9658;</small> See how everything stack up with some <%= link_to "Data", map_statistics_path %> and <%= link_to "Charts", statistics_path %></h3>
    </div>
  </div>

app/views/home/_michael_myself.html.erb
<div id="about_myself">
  <p class='description-text'>
    My name is Michael Luong, and I currently reside in San Diego.  I am a Software Engineer intern at SAIC. My primary job is to help 
    with database analysis, assist with algorithm development, and undergo module testing. As for YoloSpots, my role on the team is to
    design core funcionality schemas, implement the client side (HTML, CSS, Javascript, etc) and server side (Ruby on Rails), as well 
    as designing a business model. As for my goals in the future, I would love to get more into web development and make that a core 
    speciality of mines.
  </p>
</div>

app/views/home/_myself.html.erb
<div id="about_myself">
  <%= image_tag "la_jolla_banner.jpg", class: "display_images" %>
  <h3>About Me <small> Quy Phan</small></h3>
  <p>
    This is Quy Phan, currently working and living in San Diego.  The website is built from ground up by me and my brother Phu.
    I was mostly in charge of the mainframe of the website, i.e. bringing up the server, authentication, authorization, Facebook plugin.
    I am a Software Engineer at Qualcomm.  My area of specialty is web development both server side using Ruby on Rails
    and client side (HTML, Javascript, JQuery, CSS, etc...).  I graduated form UC San Diego with a BS Degree in Computer Science.
    My previous job was at Northrop Grumman where I was a Software Engineer intern.  My primary job there was testing, analysis,
    development and integration of Software systems.
  </p>
</div>

app/views/home/_news_feed.html.erb
<div class="accordion_2" id="accordion2">
  <div id="news_accordion_group" class="accordion-group">
    <div class="accordion-heading" id="news_accordion_head">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion5" href="#collapseFive">
        <h2><center><%=image_tag "news.png", size:"50x50", class: "accordion_header_img" %>Whats Going On?</center></h2>
      </a>
    </div>
    <div id="collapseFive" class="accordion-body collapse">
      <div class="accordion-inner">
        <div id="news_feed" class="hero-unit">
          <% @all_checkins.each_with_index do |checkin, index| %>
            <p>
              <%= checkin.message %>
              <b>With:</b>
              <% checkin.users.each do |user| %>
                <%= link_to user.name, user_path(user), :class => "user_checkin_list" %>
              <% end %>
              <b>At</b> <small style="font-size: 15px;"><%= checkin.place.name %></small>
              <b>On</b> <small style="font-size: 15px;"><%= checkin.created_at.strftime("on %A %B %d, %Y at %I:%M %p")%></small>
              <hr/>
            </p>
          <% end %>
          <center><%= paginate @all_checkins %></center>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_overview.html.erb
<div id="product_overview">
  <%= image_tag "san_diego_banner.jpg", class: "display_images" %>
  <h3>About CheckMeOut360 <small> For the common Joe </small></h3>
  <p>
    The idea started out with trying to keep track and log where you been to and who were you there with.
    Its always hard to keep track of where you go, where you ate and where you adventured to.  After couple years
    arent you curious of how many restaurants you been to? Or how many times you visited the Zoo or Seaworld?  These
    are all common questions we have.
    This problem soon transformed quickly into a web application that would help you accomplish that seamlessly and
    painfully without having to hand fill out every place you been to.  This will crawl your Facebook account
    for "check-ins" and will auto-plot this on Google Map along with useful information like 
    the store name, who were you with, etc...
  </p>
</div>

app/views/home/_phu_myself.html.erb
<div id="about_myself">
  <p class='description-text'>
  Hey my name is Phu Phan, currently working and living in San Diego. I work at Sony Computer Entertainment America.
  Loving life and enjoying everything it has to offer.  My goal for the next few months is to get CheckMeOut360 to its greatest point and adding more features to it.  What we want to do in version 2.0 of this site is to add a Yolo Spots feature page that allows the user to log into the system and see what spots are "hot" in their area for a given day.  Check us out in 360 days!
  </p>
</div>

app/views/home/_quy_myself.html.erb
<div id="about_myself">
  <p class='description-text'>
  This is Quy Phan, currently working and living in San Diego.  The website is built from ground up by me and my brother Phu.
  I was mostly in charge of the mainframe of the website, i.e. bringing up the server, authentication, authorization, Facebook plugin.
  I am a Software Engineer at Qualcomm.  My area of specialty is web development both server side using Ruby on Rails
  and client side (HTML, Javascript, JQuery, CSS, etc...).  I graduated form UC San Diego with a BS Degree in Computer Science.
  My previous job was at Northrop Grumman where I was a Software Engineer intern.  My primary job there was testing, analysis,
  development and integration of Software systems.
  </p>
</div>

app/views/home/_tan_myself.html.erb
<div id="about_myself">
  <p class='description-text'>
  Hey my name is Tan Cao and I am in charge of the business marketing aspect of CheckMeOut360!  I am currently working and living in San Diego. I work in downtown San Diego at the San Diego Housing Commission. My goal is to make this site a successful side project and hopefully make it big one day with this idea.  At the very least,  I want to gain experience and knowledge about the startup tech industry.  I believe it is a big industry and has plenty of room to grow.  I will be in charge of finding customers and attracting users.  One day, I would like to put together spreadsheets and data to present to future ventures.  That is the day we will celebrate our greatest achievements!
  <br/>
  Check us out!
  </p>
</div>

app/views/home/_technical.html.erb
<%= image_tag "jacob_school_of_engineering.jpg", class: "display_images" %>
<h3>CheckMeOut360 <small> For the Tech Wizards </small></h3>
<p>
  <b>The Web Server Side:</b> Ruby on Rails -- Ruby 1.9.2, Rails 3.1
  <br/>
  <b>Database:</b> PostgreSQL
  <br/>
  <b>Client:</b> Twitter Bootstrap, JQuery, CSS
  <br/>
  <b>Security and Authentication:</b> Devise and Omniauth
  <br/>
  <b>Mapping:</b> Google Map API, GeoCoder Gem
  <br/>
  <b>Cloud Host Server:</b> Heroku running Cedar Stack using Unicorn Rails Server
</p>

app/views/home/about.html.erb
<div id="home_page">
  <%= render 'about_page' %>
</div>

app/views/home/help.html.erb
<div class="span8">
  <%= image_tag "school_of_engineering_banner.jpg" %>
  <h3>Welcome!</h3>
  <h3>Getting Started</h3>
  <p>
    <br/>
    <b>Register using Facebook: </b>Click the <i>"login with facebook"</i> image above to sign in using Facebook
    <br/>
  </p>
  <br/>
</div>

app/views/home/index.html.erb
<% content_for :intro_message do %>
<div class='row-fluid margin-top large'>
  <div id="intro_message" class="span4 offset1">
    <h1>Welcome</h1>
    <h3> CheckMeOut-360</h3>
    <p>Where your places come alive</p>
    <h1>
      <small style="color: red">design</small> <small style="color: orange">+</small> <small style="color: blue"> develop by</small>
    </h1>
    <h2 id="ground_zero_h1" class="red underline">GroundZero Labs</h2>
  </div>
  <div id="tag_part_1" class="span3">
    <%= image_tag "computer_screens.png", size: "225x109"%>
    <br/><br/>
    <h2 class='underline'>Made for Everyone.</h2>
    <p>All you need is a Facebook Account and now you set to run
      <%= link_to "Login »", user_omniauth_authorize_path(:facebook), style: "color: red" %>. Have fun!</p>
  </div>

  <div id='tag_part_2' class='span3'>
    <%= image_tag "visualized.png", size: "225x109"%>
    <br/><br/>
    <h2 class='underline'>Simple Features.</h2>
    <p>See where you been in many different forms; from graphs to charts, to list to maps.</p>
  </div>
</div>

<% end %>

<% content_for :splash_page do %>
<div id="mini_title_bar">
  <div id="section_1_title_bar" class="span4">
    <div class="title_block">
      <br/>
      <span id="title_header">CheckMeOut 360 <span style="color: red"> Ground Zero Labs</span> </span>
    </div>
  </div>

  <div id="section_2_title_bar">
    <div id="splash_page_login_button_group">
      <% if current_user %>
        <%= link_to "Profile »", user_path(current_user), :class => "login_logout_link btn btn-primary" %>
      <% else %>
        <%= link_to "Login »", user_omniauth_authorize_path(:facebook), :class => "login_logout_link btn btn-primary" %>
      <% end %>
      &nbsp;&nbsp;
	  <%= link_to "Categories »", categories_path, :class => "btn" %>&nbsp;&nbsp;
      <%= link_to "What »", about_home_index_path, :class => "btn" %>&nbsp;&nbsp;
      <%= link_to "Who »", who_home_index_path, :class => "btn" %>
    </div>
  </div>
</div>
<% end %>

app/views/home/who.html.erb
<div>
<div id="members_navbar" class="navbar navbar-static navbar-fixed">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand nav-banner" href="#">Team Members</a>
      <ul class="nav">
        <% @users.each_with_index do |user, index| %>
        <li class=""><a href="#user_<%= user.id %>"><%= user.name %></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class='row-fluid'>
  <div class='span10 offset1'>
    <div data-spy="scroll" data-target="#members_navbar" data-offset="0" class="scrollspy-fixed">
      <% @users.each_with_index do |user, index| %>
        <div class='row-fluid'>
        <div class='span2'>
          <%= image_tag user.picture, size: "200x150", class: "avatar left pad-top img-polaroid" %>
        </div>
        <div class='span10'>
          <h4 id="user_<%= user.id %>"><%= link_to "@#{user.first_name}", user_path(:id => user.id) %></h4>
          <p><%= render :partial => "#{user.first_name}_myself", :locals => {:id => user.id}, inline: true %></p>
        </div>
        </div>
      <% end %>
    </div>
  </div>
</div>