config/routes.rb
CheckMeOut360::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "my_devise/registrations", :sessions => "my_devise/sessions" } do
    get "users/sign_in" => 'walls#index'
    get "users/sign_up" => 'walls#index'
  end
<<<<<<< HEAD
  
  resources :categories do
  end
  
=======

  resources :categories
  resources :user_extras
>>>>>>> 12333d4f6f027208e5fc5e9f7dacb8abb9671793
  resources :home, only: [:index] do
    collection do
      get 'about'
      get 'contact'
      get 'help'
      get 'who'
    end
  end
  resources :users do
    resources :places do
      collection do
        get 'map'
        get 'all_places'
        get 'sync'
      end
    end
    resources :checkins do
      collection do
        get 'sync'
      end
    end
  end

  resources :statistics, only: [:index, :map, :graph] do
    collection do
      get 'map'
      get 'graph'
      get 'pie'
      get 'line'
      get 'bar'
      get 'all_places'
    end
  end

  root :to => 'home#index'

end

app/models/facebook/place.rb
class Facebook::Place < Hashie::Trash
  property :id
  property :name
  property :location
  property :picture
  property :category
  property :checkins
  property :likes
  property :from

  def initialize(hash, graph)
    place_hash = hash
    place_hash = hash['place'] if hash.keys.include?('place')
    
    place_hash.each do |key,value|
      if key == "location"
        self[key.to_sym] = Facebook::Location.new(value)
      elsif key == "name"
        self[key.to_sym] = value
      elsif key == "id"
        self[key.to_sym] = value
        if graph
          fb_place_extra = graph.get_object(value)
          self.picture = fb_place_extra['picture']
          self.category = fb_place_extra['category']
          self.checkins = fb_place_extra['checkins']
          self.likes = fb_place_extra['likes']
        end
      end
    end
  end

end

app/models/place.rb
require 'activerecord-import'

class Place < ActiveRecord::Base
  has_many :checkins

  def build_from_checkin(checkin)
    self.address = "#{checkin.place.location.street} #{checkin.place.location.city} #{checkin.place.location.state}"
    self.name = checkin.place.name
    self.facebook_place_id = checkin.place.id
    self.facebook_id = checkin.id
    self.created_at = checkin.created_time
    self.likes = checkin.place.likes
    self.checkin_count = checkin.place.checkins
    self.picture = checkin.place.picture
    self.category = checkin.place.category
    self.lat = checkin.place.location.latitude
    self.long = checkin.place.location.longitude
  end
  
  def get_picture_for_place(graph)
    unless picture
      puts facebook_id.inspect
      begin
        place_object = graph.get_object(facebook_id)
      rescue
        return false
      end
      fb_place = Facebook::Place.new(place_object, graph)
      update_attributes(name: fb_place.name, picture: fb_place.picture, category: fb_place.category, likes: fb_place.likes, checkin_count: fb_place.checkins)
      return true
    end
  end
  
  def self.categories(time)
    rounded_time = Time.local(time.year, time.month, 1, 0, 0)
    max_time = rounded_time + 1.month
    categories = []
    token = User.me.token
    graph = Koala::Facebook::API.new(token)
    Place.where("created_at > ? and created_at < ?", rounded_time, max_time).each do |place|
      place.get_picture_for_place(graph)
      categories << place.category
    end
    return categories
  end
  
  def self.places_for_categories(category)
    Place.find_all_by_category(category)
  end
  
  def self.top_places
    top_places = {}
    places_hash = Checkin.all.group_by{|c| c.place_id}
    places_hash.each do |key,value|
      if value.count > 1
        top_places["#{Place.find(key).name}"] = value.count
      end
    end
    return Hash[top_places.sort{|a,b| b.last<=>a.last}.first(7)]
  end

  private

  def set_name_if_none_given
    if name.to_s.blank?
      address_split = address.split(" ")
      self.name = address_split.try(:first).to_s + address_split.try(:second).to_s
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter only: %w(index map) do |controller|
    controller.current_ability(current_user, @user = User.find(params[:user_id] || params[:id]))
  end

  def index
    @ability.authorize! :index, @user

    places = @user.unique_places
    @places = Kaminari.paginate_array(places).page(params[:page])
    token = User.me.token
    graph = Koala::Facebook::API.new(token)
    @places.each do |place|
      place.get_picture_for_place(graph)
    end
  end
  
  def map
    @ability.authorize! :map, @user

    @user = User.find(params[:user_id])
  end

  def all_places
    @user = User.find(params[:user_id])
    @places = @user.places
    respond_to do |format|
      format.json { render :json => @places }
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_display_single_place.html.erb
<p>
  <b>Name:</b>
  <%= @place.name %>
</p>

<p>
  <b>Address:</b>
  <%= @place.address %>
</p>

<p>
  <b>Checkins for <%=@place.name%>:</b>
  <% @place.checkins.each do |checkin| %>
    <%= link_to checkin.message, checkin_path(checkin), :class => "checkin_list btn info bottom_space" %>
  <% end %>
</p>

<%= render :partial => "google_map" %>

app/views/places/_google_map.html.erb
<div id="map_canvas" style="width:100%; height:100%"></div>

app/views/places/_places.html.erb
<%= render partial: 'shared/profile_layout', :locals => {:span_class => 'span6 offset3'} %>
<div class="clearfix"></div>
<center><%= paginate @places %></center>

<% @places.each do |place| %>
<div class="list-widget">
  <a><%= image_tag "maps.png", size: "42x42", class: "avatar left" %>
  <div class="list-head">
    <h3><a class="no-dec"><%= place.name %></a></h3>
    <div class="no-dec list-meta">Where · <a><%= place.address %></a></div>
    <p><small>On</small> <%= place.created_at.strftime("%A %B %d, %Y at %I:%M %p")%></p>
  </div>
  <div class="list_pad extra">
  <ul>
    <% place.checkins.each do |checkin| %>
      <% unless checkin.message.blank? %>
        <a>For checkins · <%="#{checkin.message}"%></a>
      <% end %>
    <% end %>
  </ul>
  </div>
</div>
<% end %>

app/views/places/create.js.erb
<% if @place.errors.any? %>
  $('#flash').html('<%= strip_new_line(render("shared/flash.html.erb", :flash => {:error => @place.errors.full_messages.join(', ')})).html_safe %>');
  return false;
<% end %>
/* Insert a place on the map */
var latlng = new google.maps.LatLng(<%= @place.lat %>,<%= @place.long%>);
// Initializes the marker (new) when address and city is entered
marker = new google.maps.Marker({
  position: latlng,
  map: map,
  animation: google.maps.Animation.DROP,
  draggable:false
});

map.setCenter(latlng);
map.setZoom(12);

infowindow = new google.maps.InfoWindow({
  content: "holding..."
});

google.maps.event.addListener(marker, 'click', function (a,b) {
  stop_bounce();
  toggle_bounce(marker);
  infowindow.setContent("<h3><%= (@place.try(:name) || @place.address) %></h3>");
  infowindow.open(map, this);
});

app/views/places/index.html.erb
<div id="profile_maps" class="profile_contents">
  <%= render :partial => "places"%>
</div>

app/views/places/list.js.erb
$('#yield_for_main_content').empty();
<% if @wall %>
  $('#yield_for_main_content').html('<%= escape_javascript(strip_new_line(render("display_places"))).html_safe %>');
<% else %>
  $('#yield_for_main_content').html('<%= escape_javascript(strip_new_line(render("shared/about"))).html_safe %>');
<% end %>

init_google_map(default_lat, default_long);
get_places_from_controller();
drop();

app/views/places/map.html.erb
<%= render partial: 'shared/profile_layout', :locals => {:span_class => 'span6 offset3'} %>
<div class="clearfix"></div>
<hr/>
<div id="profile_maps" class="profile_contents">
  <div id="current_user_profile" style="display:none;"><%=@user.id%></div>
  <%= render :partial => "google_map"%>
</div>